Applications/MmrMobile/Client/Interfaces/IMmrMobileService.cs
Applications/MmrMobile/Client/Models/Granularity.cs
Applications/MmrMobile/Client/Models/MachineInformation.cs
Applications/MmrMobile/Client/Services/MmrMobileService.cs
Applications/MmrMobile/Documentation/README.md
Applications/MmrMobile/Samples/Postman/HOMAG Connect MMR Mobile.postman_collection.json
Base/HomagConnect.Base/Documentation/README.md
Base/HomagConnect.Base/Services/ServiceBase.cs
azure-pipelines.yml

Add granularity parameter and adjust documentation

Add granularity parameter and adjust documentation

---

Applications/IntelliDivide/Contracts/Common/OptimizationBasePart.cs

Added new property for label layout value.

Added label layout property

---

Applications/MaterialManager/Contracts/Material/Boards/BoardType.cs
Applications/MaterialManager/Contracts/Material/Boards/Enumerations/CoatingCategory.cs
Applications/MaterialManager/Contracts/Material/Boards/Enumerations/MaterialCategory.cs

Add enum for materialCategory and coatingCategory

feat: add enum for coating category and material category

---

azure-pipelines.yml

deploy also package for mmr contracts to nuget.org

extend deployment of nugets for MMR

---

Applications/IntelliDivide/Contracts/Optimization.cs

add new property to check custom boards

add new property to check custom boards

---

Applications/MaterialManager/Contracts/Material/Boards/BoardType.cs
Applications/MaterialManager/Contracts/Material/Boards/Enumerations/BoardMaterialCategory.cs
Applications/MaterialManager/Contracts/Material/Boards/Enumerations/CoatingCategory.cs
Applications/MaterialManager/Contracts/Material/Edgebands/EdgebandType.cs
Applications/MaterialManager/Contracts/Material/Edgebands/EdgebandTypeDetails.cs
Applications/MaterialManager/Contracts/Material/Edgebands/EdgebandTypeInventory.cs
Applications/MaterialManager/Contracts/Material/Edgebands/Enumerations/EdgebandMaterialCategory.cs
Applications/MaterialManager/Contracts/Material/Edgebands/Enumerations/GluingCategory.cs
Base/HomagConnect.Base.Contracts/Enumerations/BaseUnit.cs
Base/HomagConnect.Base/Extensions/ContainsUnitSystemDependentPropertiesExtensions.cs
homag-connect.sln.DotSettings

feat: adjust edgeband model and add necessary enums + values conversions

feat: adjust edgeband model

---

Applications/IntelliDivide/Samples/Requests/Nesting/NestingOptimizationUsingObjectModel.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestTests.cs

intelliDivide nesting solution details

intelliDivide nesting solution details

---

Applications/MaterialManager/Client/MaterialManagerClientProcessingOptimization.cs
Applications/MaterialManager/Tests/Processing/Optimization/ProcessingOptimizationTests.cs

fix: fix parameters within client for offcut parametersets

fix: fix parameters within client for offcut parametersets

---

Applications/MaterialManager/Client/MaterialManagerClientMaterialBoards.cs
Applications/MaterialManager/Client/MaterialManagerClientMaterialEdgebands.cs

fix: fix url creation for board and edgebandTypes

fix: fix url creation for board and edgebandTypes

---

Applications/MaterialManager/Client/MaterialManagerClientMaterialBoards.cs
Applications/MaterialManager/Client/MaterialManagerClientMaterialEdgebands.cs

fix: fix wrong url creation for board and edgebandTypes

fix: fix wrong url creation for board and edgebandTypes

---

Applications/MaterialManager/Contracts/Material/Boards/BoardType.cs
Applications/MaterialManager/Contracts/Material/Edgebands/EdgebandType.cs

[add](feat: added GTIN to BoardType and EdgebandType)

feat: added GTIN to BoardType and EdgebandType

---

Applications/MaterialManager/Client/MaterialManagerClientMaterialBoards.cs

fix: add missing boardCode into url creation for update boardType client method

fix: add missing boardCode into url creation for update boardType client method

---

Applications/MaterialAssist/Samples/Postman/Homag Connect materialAssist.postman_collection.json
Applications/MaterialManager/Samples/Postman/Homag Connect materialManager.postman_collection.json

feat: update postman collections for materialManager and materialAssist

feat: update postman collections for materialManager and materialAssist

---

Applications/MaterialManager/Samples/Postman/Homag Connect materialManager.postman_collection.json

feat: extend postman collection for material manager update edgeband types

feat: extend postman collection for material manager update edgeband types

---

Applications/IntelliDivide/Tests/Requests/Cutting/OptimizationRequestTests.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestTests.cs
Applications/IntelliDivide/Tests/Results/OptimizationResultTests.cs
Applications/MaterialManager/Tests/Read/Boards/MaterialManagerReadBoardsResult.cs
Applications/MmrMobile/Tests/MmrMobileClientTests.cs
Base/HomagConnect.Base.Contracts/Extensions/UnitSystemExtensions.cs

…nstraintsfeat: add rounding for calculated areas alligned with our property constraints

feat: add rounding for calculated areas alligned with our property constraints

---

Applications/MaterialManager/Contracts/Material/Boards/BoardType.cs

fix: rename property MaterialLastUsedDate to MaterialLastUsed

fix: rename property MaterialLastUsedDate to MaterialLastUsed

---

Applications/IntelliDivide/Contracts/Result/SolutionOverviewFiguresMaterial.cs

Updated offcuts properties to be in-line with the material depending parameters changes.

Updated offcuts properties

---

Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/OffcutParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TrimCutParameterSet.cs

Added default group property for material depending parameters

feat: Add default group bool property

---

Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestTests.cs
Applications/ProductionManager/Client/ProductionManagerClient.cs
Applications/ProductionManager/Contracts/IProductionManagerClient.cs
Applications/ProductionManager/Contracts/Predict/CuttingPrediction.cs
Applications/ProductionManager/Contracts/Predict/CuttingPredictionPart.cs
Applications/ProductionManager/Contracts/Predict/CuttingPredictionRequest.cs
Applications/ProductionManager/Contracts/Predict/EdgebandingPrediction.cs
Applications/ProductionManager/Contracts/Predict/EdgebandingPredictionPart.cs
Applications/ProductionManager/Contracts/Predict/EdgebandingPredictionRequest.cs
Applications/ProductionManager/Contracts/Predict/PredictionMachineData.cs
Applications/ProductionManager/Samples/Orders/Predict/PredictParts.cs
Applications/ProductionManager/Tests/Predict/EdgebandingPredictionTests.cs

Extend models for prediction (dedicated predictions per machinenumber, when calculating for a subscription)

change Model for cuttingPrediction

---

Applications/ProductionManager/Contracts/Predict/PredictionMachineData.cs
Applications/ProductionManager/Samples/Orders/Predict/PredictParts.cs
Applications/ProductionManager/Tests/Predict/EdgebandingCuttingTests.cs
Applications/ProductionManager/Tests/Predict/EdgebandingPredictionTests.cs

extend test for cutting prediction

add property machinename

---

Applications/IntelliDivide/Tests/Requests/Cutting/OptimizationRequestTests.cs
Applications/MaterialManager/Tests/Read/Boards/MaterialManagerReadBoardsResult.cs
Applications/MmrMobile/Samples/AlertsEvents/AlertEventsSamples.cs
Applications/MmrMobile/Samples/MmrConsole.cs
Applications/ProductionManager/Client/ProductionManagerClient.cs
Applications/ProductionManager/Contracts/IProductionManagerClient.cs
Applications/ProductionManager/Contracts/Predict/CncPrediction.cs
Applications/ProductionManager/Contracts/Predict/CncPredictionPart.cs
Applications/ProductionManager/Contracts/Predict/CncPredictionRequest.cs
Applications/ProductionManager/Samples/Orders/Predict/PredictParts.cs
Applications/ProductionManager/Tests/Predict/CncPredictionTests.cs
Applications/ProductionManager/Tests/Predict/CuttingPredictionTests.cs
Base/HomagConnect.Base/Services/ServiceBase.cs

2 corrections due to sonar-hints

define model for Cnc Prediction

---

Applications/MaterialAssist/Contracts/Edgebands/EdgebandEntity.cs

fix: remove property height out of edgebandEntity model

fix: remove property height out of edgebandEntity model

---

Applications/IntelliDivide/Samples/Requests/CommonSettings.cs
Applications/IntelliDivide/Samples/Requests/Cutting/CuttingOptimizationUsingObjectModel.cs
Applications/IntelliDivide/Samples/Requests/Nesting/NestingOptimizationUsingObjectModel.cs
Applications/IntelliDivide/Samples/Requests/Nesting/NestingOptimizationUsingProjectZip.cs
Applications/IntelliDivide/Samples/Requests/Template/Cutting/CuttingRequestUsingTemplateSamples.cs
Applications/IntelliDivide/Samples/Requests/Template/Nesting/NestingRequestUsingTemplateSamples.cs

Extended timeout for intelliDivide tests.

Extended timeout

---

Applications/MaterialAssist/Client/MaterialAssistClientEdgebands.cs
Applications/MaterialAssist/Contracts/Edgebands/EdgebandEntity.cs
Applications/MaterialAssist/Contracts/Edgebands/Interfaces/IMaterialAssistClientEdgebands.cs
Applications/MaterialAssist/Contracts/Update/MaterialAssistUpdateEdgebandEntity.cs

refactor: refactor materialAssistUpdateEdgebandEntity functionality and models

refactor: refactor materialAssistUpdateEdgebandEntity functionality and models

---

Applications/IntelliDivide/Samples/Requests/Cutting/CuttingOptimizationUsingObjectModel.cs
Applications/ProductionAssist/Tests/Feedback/ProductionAssistFeedbackTests.cs
Applications/ProductionManager/Tests/Predict/CncPredictionTests.cs
Applications/ProductionManager/Tests/Predict/CuttingPredictionTests.cs
Applications/ProductionManager/Tests/Predict/EdgebandingPredictionTests.cs

Adjusted intelliDivide test after validation implementation.

Adjusted intelliDivide test after validation implementation

---

Applications/IntelliDivide/Samples/Requests/Cutting/CuttingOptimizationUsingObjectModel.cs
Applications/IntelliDivide/Tests/Requests/Cutting/OptimizationRequestTests.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestTests.cs
Applications/IntelliDivide/Tests/Statistics/MaterialStatisticTests.cs

Enabled all intelliDivide tests.

Enabled all intelliDivide tests

---

Applications/IntelliDivide/Samples/Requests/Nesting/NestingOptimizationUsingObjectModel.cs
Applications/IntelliDivide/Samples/Requests/Nesting/NestingOptimizationUsingProjectZip.cs

Updated timeouts for intelliDivide tests.

Updated timeouts for intelliDivide tests

---

Applications/IntelliDivide/Samples/Requests/CommonSettings.cs

Extended timeout to account for waiting azure functions.

Extended timeout to account for waiting azure functions

---

Applications/IntelliDivide/Contracts/Result/SolutionDetails.cs

Removed redundant patterns property. The property is already available in SolutionOverview.

Removed redundant patterns property

---

Applications/IntelliDivide/Contracts/Statistics/MaterialEfficiency.cs

Compute the total cost for the material used

Add the cost parameters to the material efficiency model. 

---

Applications/IntelliDivide/Client/IntelliDivideClient.cs
Applications/IntelliDivide/Contracts/IIntelliDivideClient.cs
Applications/IntelliDivide/Tests/Statistics/StatisticTests.cs
Base/HomagConnect.Base/HttpResponseMessageExtensions.cs

Extend the IntelliDivide client to provide the edgeband statistics

Extend IntelliDivide client to provide the edgeband statistics

---

Applications/IntelliDivide/Tests/Requests/Cutting/CuttingOptimizationRequestTests.cs
Applications/IntelliDivide/Tests/Requests/Cutting/CuttingOptimizationRequestUsingObjectModelTests.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestCommonTests.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestUsingObjectModelTests.cs

Enabled intelliDivide tests now that Gateway API was released to PRD.

Enabled intelliDivide tests

---

Applications/MaterialManager/Contracts/Material/Boards/BoardType.cs
Applications/MaterialManager/Contracts/Request/MaterialManagerRequestBoardType.cs
Applications/MaterialManager/Contracts/Update/MaterialManagerUpdateBoardType.cs

feat: add density

---

Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimType.cs

extended the tension trim model 
https://dev.azure.com/homag-group/OneHomag/_workitems/edit/308362/

feat: add parameters to tensionTrim model

---

Applications/MaterialManager/Contracts/Processing/Optimization/BookheightMode.cs
Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameters.cs
Applications/MaterialManager/Tests/Statistics/PartHistoryStatisticsTests.cs

added the new parameter and marked old as obsolete

feat: add new parameter

---

Applications/IntelliDivide/Contracts/Common/OptimizationBasePart.cs
Applications/IntelliDivide/Tests/Optimizations/OptimizationsRetrievalTests.cs
Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestCommonTests.cs

Added some properties to OptimizationBasePart class that were missing, but still being used by productionManager when importing orders.

Added missing part properties

---

Applications/IntelliDivide/Tests/Requests/Nesting/NestingOptimizationRequestUsingProjectZipTests.cs
Applications/MaterialManager/Contracts/Processing/Optimization/MachineParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/MachineParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TrimCutParameterSet.cs

added machine parameter models

feat: machine parameter models

---

Applications/MaterialManager/Contracts/Processing/Optimization/BookheightMode.cs
Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameters.cs

removed one parameter and mode from the bookheight parameters and added a new one

feat: replace bookheight parameter

---

Applications/MaterialManager/Contracts/Processing/Optimization/MachineParameters.cs

feat: Add new property and make machineParameter obsolete

---

Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/MachineParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/OffcutParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameterSet.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TrimCutParameterSet.cs

made the link nullable to remove it in the future with no deserialization issues

feat: make the link obsolete and nullable

---

.github/workflows/action.yml

https://github.com/dotnet/source-build/blob/main/.github/workflows/check-markdown-links.yml

Link checker prototype (copied from github of dotnet)

---

Applications/OrderManager/Contracts/OrderItems/Configuration.cs
Applications/OrderManager/Contracts/OrderItems/ConfigurationAttribute.cs
Applications/OrderManager/Contracts/OrderItems/ConfigurationPosition.cs
Applications/OrderManager/Tests/Orders/GetOrderTests.cs
Base/HomagConnect.Base.Contracts/Interfaces/IConfiguration.cs
Base/HomagConnect.Base.Contracts/Interfaces/IConfigurationAttribute.cs

Changed "Attributes" from Dictionary to a Collection

The attributes of a configuration is now an object to handle the case of input/output attributes

---

Applications/MaterialManager/Contracts/Material/Edgebands/EdgebandType.cs
Applications/MaterialManager/Contracts/Request/MaterialManagerRequestEdgebandType.cs
Applications/MaterialManager/Contracts/Update/MaterialManagerUpdateEdgebandType.cs
Applications/MaterialManager/Samples/Postman/Homag Connect materialManager.postman_collection.json
Applications/MaterialManager/Tests/Create/Edgebands/CreateEdgebandTypeTests.cs
Applications/MaterialManager/Tests/Material/Edgebands/EdgebandTypeTests.cs

EdgebandType Length property has to be DefaultLength

feat: default length for edgeband type

---

Applications/MaterialAssist/Contracts/Request/MaterialAssistRequestBoardEntity.cs
Applications/MaterialAssist/Contracts/Request/MaterialAssistRequestEdgebandEntity.cs

ManagementType represents a mandatory property

feat: ManagementType not nullable

---

Applications/MaterialManager/Samples/Postman/Homag Connect materialManager.postman_collection.json

Add the macro and machine GET requests. Update the Create and Update request for EdgebandTypes with the technology macro for machines

feat: update Postman

---

Applications/IntelliDivide/Tests/Requests/Cutting/CuttingOptimizationRequestUsingObjectModelTests.cs
Applications/MaterialAssist/Contracts/Request/MaterialAssistRequestBoardEntity.cs
Applications/MaterialAssist/Contracts/Request/MaterialAssistRequestEdgebandEntity.cs
Applications/MaterialAssist/Contracts/Request/MaterialAssistRequestOffcutEntity.cs
Applications/MaterialAssist/Samples/Create/Offcuts/Readme.md
Applications/MaterialAssist/Samples/Postman/Homag Connect materialAssist.postman_collection.json

Allow offcut entity creation with quantity > 1.

feat: Enable offcut entity creation with custom quantity

---

Applications/MmrMobile/Contracts/MachineCounter.cs
Applications/MmrMobile/Contracts/MachineInformation.cs
Applications/MmrMobile/Contracts/MachineState.cs
Applications/MmrMobile/Contracts/MmrMachine.cs

Refine Mmr Mobile Data Contracts

Update Mmr Mobile Contracts

---

Applications/OrderManager/Samples/Postman/Homag Connect orderManager.postman_collection.json
Applications/OrderManager/Tests/Import/ImportOrderTests.cs
Applications/OrderManager/Tests/Orders/GetOrderTests.cs

Extend Temp Disable tests for oM

Adjust Postman Collection for oM. Extend Temp Disabled Tests for oM

---

Applications/IntelliDivide/Samples/Postman/HOMAGConnectIntelliDivide.postman_collection.json

- Get Boards
- Get Edgebands
- Get localized texts for enums

Postman intelliDivide samples extended

---

Applications/IntelliDivide/Samples/Postman/HOMAGConnectintelliDivide.postman_collection.json
Applications/OrderManager/Samples/CSharp/Orders/Actions/GetOrderSamples.cs
DataExchange/Contracts/Project.cs
DataExchange/Extensions/ProjectExtensionsConversion.cs
DataExchange/Extensions/ProjectExtensionsVersioning.cs
DataExchange/Extensions/ProjectPersistenceManager.cs
DataExchange/Extensions/Wrapper/ProjectWrapper.cs
DataExchange/Tests/ConversionTests.cs
DataExchange/Tests/HomagConnect.DataExchange.Tests.csproj
DataExchange/Tests/MigrationTests.cs
DataExchange/Tests/ProjectReadTests.cs

ProjectPersistenceManagaer introduced.
Extension MigrateToLatestVersion added.

Project.xml version handling added

---

Applications/OrderManager/Client/OrderManagerClient.cs
Applications/OrderManager/Tests/Import/ImportOrderTests.cs
Applications/OrderManager/Tests/OrderManagerTestBase.cs
Base/HomagConnect.Base/Extensions/MultipartFormDataContentExentions.cs
DataExchange/Extensions/ProjectExtensionsConversion.cs
DataExchange/Extensions/Wrapper/EntityWrapper.cs
DataExchange/Extensions/Wrapper/EntityWrapperList.cs
DataExchange/Extensions/Wrapper/OrderItemWrapper.cs

Set Catalog in tests.
Set PersonInCharge in tests.
Compress files when it makes sense.
Extend timeout.

OrderManager import extended

---

Applications/MaterialManager/Contracts/Processing/Optimization/BookheightParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/OffcutParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TensionTrimParameters.cs
Applications/MaterialManager/Contracts/Processing/Optimization/TrimCutParameters.cs

feat: add attributes

---

Applications/MaterialAssist/Client/MaterialAssistClientEdgebands.cs
Applications/MaterialAssist/Contracts/Edgebands/IMaterialAssistClientEdgebands.cs
Applications/MaterialAssist/Samples/Postman/Homag Connect materialAssist.postman_collection.json

Added a new request in the Postman collection for storing an edgeband entity, including a sample JSON body.

feat: store edgeband entities latest updates, refactoring

---

Applications/IntelliDivide/Tests/Requests/Cutting/CuttingOptimizationRequestUsingObjectModelTests.cs
Applications/MaterialManager/Tests/Material/Boards/BoardTypeTests.cs
Applications/OrderManager/Samples/Postman/Homag Connect orderManager.postman_collection.json

Added delete customers functionality

Update Homag Connect orderManager.postman_collection.json

---

Applications/MaterialManager/Samples/Postman/Homag Connect materialManager.postman_collection.json

adds the endpoint to get materials to postman

feat: add getMaterials to postman collection

---

Applications/IntelliDivide/Contracts/Optimization.cs
Applications/IntelliDivide/Contracts/Result/Solution.cs

Add properties for marking the transferred solution of an optimization.

Add properties for marking the transferred solution

---

Applications/IntelliDivide/Client/IntelliDivideClient.cs
Applications/IntelliDivide/Contracts/IIntelliDivideClient.cs
Applications/IntelliDivide/Samples/CSharp/Optimizations/OptimizationRetrievalSamples.cs
Applications/IntelliDivide/Tests/Optimizations/OptimizationsRetrievalTests.cs

(cherry picked from commit 8c4694f4e7a23dfa1e8356eb43f7ee7f53cf2454)

Retrieve list of available exports for a solution

---

Applications/MaterialAssist/Tests/EdgebandEntities/EdgebandEntityTests.cs

Enabled edgeband storing tests

feat: enable edgeband storing tests

---

Applications/MmrMobile/Client/MmrMobileClient.cs
Applications/MmrMobile/Contracts/IMmrMobileClient.cs
Applications/MmrMobile/Tests/MmrMobileClientTests.cs
Applications/ProductionAssist/Tests/ProductionAssistTests.cs

new endpoint in Mmr Mobile for upload a file containing a productionProtocol

Client method for uploading a HOL file from FileAgent

---

Applications/ProductionManager/Client/ProductionManagerClient.cs
Applications/ProductionManager/Contracts/IProductionManagerClient.cs
Applications/ProductionManager/Samples/Postman/Homag Connect productionManager.postman_collection.json

feat: add client methods and update postman collection to get lots and lot details

feat: add client methods and update postman collection to get lots and lot details

---

Applications/IntelliDivide/Contracts/Common/OptimizationBasePart.cs
Applications/IntelliDivide/Samples/CSharp/Requests/Cutting/ObjectModel/CuttingRequestUsingObjectModelSamples.cs
homag-connect.sln.DotSettings

Property DestackingGroup renamed to fit app translation.
Property DestackingDestination introduced to support flexTec machines.

intelliDivide Destacking properties adjusted

---

DataExchange/ImportSpecification.md

Updated documentation for import parameters.

Updated documentation for import parameters

---

Applications/MaterialManager/Samples/Create/Boards/CreateBoardtypeSamples.cs
Applications/MaterialManager/Samples/Create/Boards/Readme.md
Applications/MaterialManager/Samples/Create/Edgebands/CreateEdgebandTypeSamples.cs
Applications/MaterialManager/Samples/Create/Edgebands/Readme.md
Applications/MaterialManager/Tests/Create/Edgebands/CreateEdgebandTypeTests.cs

feat: improve samples

---

Applications/IntelliDivide/Contracts/Result/SolutionPart.cs
Applications/IntelliDivide/Contracts/Result/SolutionPattern.cs
azure-pipelines.yml

Add zip identifiers for nesting parts and patterns for production protocol implementation.

Add zip identifiers for nesting parts and patterns

---

Applications/ProductionAssist/Client/ProductionAssistCuttingClient.cs
Applications/ProductionAssist/Client/ProductionAssistNestingClient.cs
Applications/ProductionManager/Client/ProductionManagerClient.cs

fix: replace vulnerable for loops by stable linq queries

fix: replace vulnerable for loops by stable linq queries

---

Applications/ProductionManager/Contracts/ProductionProtocol/ProcessedPartCnc.cs
Applications/ProductionManager/Tests/ProductionProtocol/ProductionProtocolTests.cs

Add OrderName, OrderId, Preview Image Uri, CustomerName, StartedAt and CompletedAt parameters for ProcessedPartCnc

Add additional parameters for ProductionProtocol ProcessedPartCnc
